tls:
  certificates:
    - certFile: /certs/api.faskplusai.dev.pem
      keyFile: /certs/api.faskplusai.dev-key.pem
    - certFile: /certs/faskplusai.dev.pem
      keyFile: /certs/faskplusai.dev-key.pem
